// Map Team Name → ISO 2-letter code (lowercase filenames)
export const FLAG_CODE = {
  Mexico: "mx",
  Canada: "ca",
  "United States": "us",

  Spain: "es",
  Argentina: "ar",
  France: "fr",
  England: "gb-eng",
  Brazil: "br",
  Portugal: "pt",
  Netherlands: "nl",
  Belgium: "be",
  Germany: "de",

  Croatia: "hr",
  Morocco: "ma",
  Colombia: "co",
  Uruguay: "uy",
  Switzerland: "ch",
  Japan: "jp",
  Senegal: "sn",
  Iran: "ir",
  "South Korea": "kr",
  Ecuador: "ec",
  Austria: "at",
  Australia: "au",

  Norway: "no",
  Panama: "pa",
  Egypt: "eg",
  Algeria: "dz",
  Scotland: "gb-sct",
  Paraguay: "py",
  Tunisia: "tn",
  "Ivory Coast": "ci",
  Uzbekistan: "uz",
  Qatar: "qa",
  "Saudi Arabia": "sa",
  "South Africa": "za",

  Jordan: "jo",
  "Cape Verde": "cv",
  Ghana: "gh",
  Curaçao: "cw",
  Haiti: "ht",
  "New Zealand": "nz",
  Iraq: "iq",
  "DR Congo": "cd",

  Italy: "it",
  Poland: "pl",
  Turkey: "tr",
  Denmark: "dk",
};
